#!/bin/bash
set -e

echo "installing tmux"
sudo apt install tmux

echo "config tmux"
cp ~/.vim_runtime/.tmux.conf  ~

echo "installing miktex"
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
echo "deb http://miktex.org/download/ubuntu focal universe" | sudo tee /etc/apt/sources.list.d/miktex.list
sudo apt-get update
sudo apt-get install miktex
miktexsetup finish
initexmf --set-config-value [MPM]AutoInstall=1

echo "installing neovim"
sudo apt install neovim

echo "pip install pyvim and neovim-remote"
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pynvim  neovim-remote

cd ~/.vim_runtime

echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/vimrcs/my_basic.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
source ~/.vim_runtime/vimrcs/vundle.vim
source ~/.vim_runtime/vimrcs/my_plungins.vim
source ~/.vim_runtime/vimrcs/my_basic.vim
' > ~/.vimrc

mkdir -p ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim




echo "Disable the stty shortcuts such as ctrl s, for neovim will use them."
echo "stty -ixon" >> ~/.bashrc

echo "installing formate of different type of filse used by vim-autoformat"
conda install latexindent.pl -c conda-forge

echo "installing okular"
sudo apt install okular

echo "installing recycle bin for linux"
sudo apt install trash-cli
echo "alias vi=nvim" >> ~/.bashrc
echo "alias vim=nvim" >> ~/.bashrc
echo "alias rm=trash-put" >> ~/.bashrc

echo "Installed the Vim configuration successfully! Enjoy :-)"
echo "For Latex backwordsearch support, you need to add \"nvr --remote-silent +%l %f\" to your okular "




