#!/bin/bash
set -e

cd ~
mkdir temp_try
echo -e "\033[31m installing node \033[0m"
wget https://nodejs.org/dist/v17.6.0/node-v17.6.0-linux-x64.tar.xz
tar xf node-v17.6.0-linux-x64.tar.xz
mv node-v17.6.0-linux-x64 node
sudo ln -s ~/node/bin/node /usr/bin/node
sudo ln -s ~/node/bin/npm /usr/bin/npm
npm i hexo-cli -g

echo -e "\033[31m installing tmux \033[0m"
sudo apt install tmux -y

echo -e "\033[31m config tmux \033[0m"
cp ~/.vim_runtime/.tmux.conf ~

# echo -e "\033[31m installing miktex \033[0m"
# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys D6BC243565B2087BC3F897C9277A7293F59E4889
# echo "deb http://miktex.org/download/ubuntu focal universe" | sudo tee /etc/apt/sources.list.d/miktex.list
# sudo apt-get update
# sudo apt-get install miktex -y
# miktexsetup finish
# initexmf --set-config-value [MPM]AutoInstall=1

echo -e "\033[31m installing texlive \033[0m"
mkdir texlive
cd texlive
wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
tar -zxvf install-tl-unx.tar.gz
cd install-tl-20220302
sudo perl install-tl

echo -e "\033[31m installing neovim \033[0m"
sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt install neovim -y

echo -e "\033[31m pip install pyvim and neovim-remote \033[0m"
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pynvim neovim-remote

cd ~/.vim_runtime

echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/vimrcs/my_basic.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
source ~/.vim_runtime/vimrcs/vundle.vim
source ~/.vim_runtime/vimrcs/my_plungins.vim
source ~/.vim_runtime/vimrcs/my_basic.vim
' >~/.vimrc

mkdir -p ~/.config/nvim
ln -s ~/.vimrc ~/.config/nvim/init.vim

echo -e "\033[31m Disable the stty shortcuts such as ctrl s, for neovim will use them. \033[0m"
echo "stty -ixon" >>~/.bashrc

echo -e "\033[31m installing formate of different type of filse used by vim-autoformat \033[0m"
conda install latexindent.pl -c conda-forge
sudo apt install golang-go -y
export GO111MODULE=on
go env -w GOPROXY=https://goproxy.cn
go get -u mvdan.cc/sh/cmd/shfmt
echo "export PATH=\"~/go/bin:\$PATH\"" >>~/.bashrc
echo "export PATH=\"~/node/bin:\$PATH\"" >>~/.bashrc
npm install -g remark-cli
npm install prettier remark-prettier -g

echo -e "\033[31m installing okular \033[0m"
sudo apt install binutils -y
sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
sudo apt install okular -y

echo -e "\033[31m installing recycle bin for linux \033[0m"
sudo apt install trash-cli -y
echo "alias vi=nvim" >>~/.bashrc
echo "alias vim=nvim" >>~/.bashrc
echo "alias rm=trash-put" >>~/.bashrc

echo "alias ctp=\'cd ~/temp_try\'" >>~/.bashrc
echo "alias cvi=\'cd ~/.vim_runtime\'" >>~/.bashrc
echo "alias cbg=\'cd ~/myBlog\'" >>~/.bashrc
echo "alias cpp=\'cd ~/mypaper\'" >>~/.bashrc
echo "alias cltp=\'rm -rf ~/temp_try/*\'" >>~/.bashrc

echo -e "\033[31m allow to fill the bash variable in the command line in tab \033[0m"
echo "shopt -s direxpand" >>~/.bashrc
echo "de=\"/mnt/c/Users/12197/Desktop\"" >>~/.bashrc
echo "de=\"/mnt/c/Users/12197/Downloads\"" >>~/.bashrc

cd ~
echo -e "\033[31m clone my blog \033[0m"
git clone -b hexo git@github.com:xyegithub/myBlog.git

echo -e "\033[31m For Latex backwordsearch support, you need to add \"nvr --remote-silent +%l %f\" to your okular \033[0m"
echo -e "\033[31m For Latex backwordsearch support, you need to add \"nvr --remote-silent +%2 %1\" to your qpdfview \033[0m"
echo -e "\033[31m run :PluginInstall in your vim for installing some plugins \033[0m"
